### ISSUE TITLE
Make JSON-Schema for netkan files?

### ISSUE THREAD

**Issue by janbrohl** [KSP-CKAN/xKAN-meta_testing#14]
Not sure if this belongs here or should go to https://github.com/KSP-CKAN/CKAN/issues

[JSON-Schema](http://json-schema.org/) allows for JSON validation via Javascript (as well as [other languages](http://json-schema.org/implementations.html#validator-list))

This would be useful for the metadata-webtool - see https://github.com/KSP-CKAN/metadata-webtool/issues/6

For ckan files this already exists ( see https://github.com/KSP-CKAN/CKAN/blob/master/CKAN.schema ) and a netkan schema can propably be built on that.

**Comment by techman83** [comment]
Technically NetKAN is a subset of a CKAN, so any field in a CKAN is valid in a NetKAN. All CKANs are now generated using NetKAN. The primary difference is that a traditional NetKAN takes a '$kref' for inflating the rest of the data, including the version of the mod.

We would just need a minor derivative to not require a download or version if a kref is present.
