### ISSUE TITLE
NetKAN Testing Doesn't Check Schema

### ISSUE THREAD

**Issue by techman83** [KSP-CKAN/xKAN-meta_testing#2]
@plague006 noted invalid licenses get a clear during testing of Netkans. For reference KSP-CKAN/NetKAN#3715 and KSP-CKAN/NetKAN#3717.

The indexer wouldn't have indexed them, but it'd be better to catch it here.

**Comment by plague006** [comment]
https://github.com/KSP-CKAN/NetKAN/issues/3278
