### ISSUE TITLE
Indexer should throw up a red flag/halt if we try to install a `GameData` folder

### ISSUE THREAD

**Issue by plague006** [KSP-CKAN/xKAN-meta_testing#3]
https://github.com/KSP-CKAN/NetKAN/pull/3693 is the most recent example, but it'd be nice to be able to catch these types of errors as when they do occur they're majorly disruptive (packaged dependencies being double-installed).

If this is more the domain of the ckan client or netkan let me know and I'll re-create in the CKAN repo.

**Comment by techman83** [comment]
Shouldn't be super difficult.
```
leon@beast /tmp $ find GameData/. -name GameData
GameData/./SomeOtherMod/GameData
GameData/./SomeMod With Spaces/GameData
GameData/./Somemod/GameData
leon@beast /tmp $ find GameData/. -name GameData -exec sh -c 'if test -d "{}"; then echo "GameData Found!";fi' \;
GameData Found!
GameData Found!
GameData Found!
```

**Comment by techman83** [comment]
http://ci.ksp-ckan.org/job/NetKAN/2979/console

**Comment by techman83** [comment]
PR opened @plague006

**Comment by plague006** [comment]
You're a beast techman.

**Comment by techman83** [comment]
Hahaha, thanks! :D
