### ISSUE TITLE
Build Docker Container on repo change

### ISSUE THREAD

**Issue by techman83** [KSP-CKAN/xKAN-meta_testing#30]
- Easier deployment of Container changes
- Possibly include build scripts inside of container to avoid downloading on every build
- other things?

**Comment by HebaruSan** [comment]
Is it just a matter of adding this to `build.sh`?

`docker build -t ckan-ci`

**Comment by techman83** [comment]
Hmm, we probably don't want it building _every_ time. Also we're inside the container at that point too, so any changes won't end when we need them.

https://dantehranian.wordpress.com/2014/10/25/building-docker-images-within-docker-containers-via-jenkins/

Probably better to use travis + and push the container into docker hub or something. The job can be configured to pull the image from a remote repo.

We've only changed the container 3 times in 3 years, so it hasn't been a super big deal yet.

**Comment by HebaruSan** [comment]
I think this doesn't apply anymore after #61 because now we will use containers generated by the GitHub Action system.
