### ISSUE TITLE
[Bug] Inflating way too many things with weird git branches

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/xKAN-meta_testing#66]
## Problem

If a PR is submitted with unusual branching, the validation scripts can inflate _way_ too many netkans and take way way too much time (KSP-CKAN/NetKAN#8292 initially took 1h+, and it hadn't even finished!):

- https://github.com/KSP-CKAN/NetKAN/actions/runs/453386320

![image](https://user-images.githubusercontent.com/1559108/103384599-99d34900-4abc-11eb-8aa6-27661f65f7e3.png)

## Workarounds

I cancelled that run and rebased the PR's branch off of master. Actual time needed was just over 1 minute:

- https://github.com/KSP-CKAN/NetKAN/actions/runs/453489136

![image](https://user-images.githubusercontent.com/1559108/103384714-ffbfd080-4abc-11eb-8f20-b11735a5277a.png)

## Causes

I think this mainly happens when a local master branch is updated by creating merge commits from the actual master. It's surprisingly hard to get the list of files affected by a pull request. I don't exactly know how GitHub does it. Here's the current logic:

https://github.com/KSP-CKAN/xKAN-meta_testing/blob/a30551b921699106eff6093d7fcad8c3066b35bb/ckan_meta_tester/ckan_meta_tester.py#L182-L221

## Suggestions

At a minimum, we should probably have some absolute upper limit on the number of netkans inflated per pull request. If we hit that limit and print an error and fail, a team member can step in with a rebase.

Ideally we should replicate GitHub's logic for figuring out the changed files. I thought that's what we did, but I guess not.

**Comment by DasSkelett** [comment]
If I'm reading the code right, we are currently iterating over all commits, and adding every file changed in each commit to the list of changed netkans. In case of "update my fork" merge commits like in https://github.com/KSP-CKAN/NetKAN/pull/8292, this can be a lot.

Instead we should try to get the total diff compared to the base branch, and only the files that got changed in this total diff.
Don't know how easy this is with gitpython, maybe the old bash scripts can give us a hint?

**Comment by HebaruSan** [comment]
Great idea, go for it!

**Comment by HebaruSan** [comment]
> iterating over all commits, and adding every file changed in each commit to the list of changed netkans

That _was_ my attempt to "get the total diff compared to the base branch", cringe emoji.
