### ISSUE TITLE
PRs into the wrong folders

### ISSUE THREAD

**Issue by plague006** [KSP-CKAN/xKAN-meta_testing#7]
It's rare, easy to spot, and easy to fix each case so it's certainly not a high priority but if Jenkins could be made to catch PRs into the wrong folders it's 1 less error humans can make.

**Comment by techman83** [comment]
@plague006 do we need this now that NetKAN is doing all the heavy lifting?

**Comment by plague006** [comment]
I meant .netkans going into the NetKAN folder.

Ex. https://github.com/KSP-CKAN/NetKAN/commit/03ff2cdfc753e5b1bb71700ff5e9b7dcaef74788

**Comment by techman83** [comment]
@plague006 Aha, yes. That should be pretty easy. CKANs would have been more challenging, but not impossible.

**Comment by techman83** [comment]
Ok, I'll have a PR soon that will cover this off.

```
leon@beast /tmp/test/NetKAN $ ./build.sh test
Using CLI argument of test
Commit hash: test
NetKAN file found in root of repository, please move it into NetKAN/
leon@beast /tmp/test/NetKAN $ echo $?
3
```
