### ISSUE TITLE
[Bug] Testing modules changed on master after branch creation

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/xKAN-meta_testing#73]
## Problem

1. Submit a NetKAN PR branched from current master
2. The correct modules will be tested
3. Merge some other changes into master for some other module(s)
4. Add a new commit to the PR from step 1
5. The modules from step 3 will be tested as well

Probably related to #66.

## Background

This already shouldn't happen because we determine the files to test by diffing HEAD with GITHUB_PR_BASE_SHA (passed via PR_BASE_SHA env var because GITHUB_ prefixes are forbidden).

https://github.com/KSP-CKAN/xKAN-meta_testing/blob/fddb638ef5b16599ef6d2fdf2866eb5709bdfadc/ckan_meta_tester/ckan_meta_tester.py#L42-L45

https://github.com/KSP-CKAN/xKAN-meta_testing/blob/fddb638ef5b16599ef6d2fdf2866eb5709bdfadc/ckan_meta_tester/ckan_meta_tester.py#L195-L209

The value definitely gets passed:

![image](https://user-images.githubusercontent.com/1559108/114067294-319abd00-988c-11eb-80a5-93f625f1c56d.png)

And our checkouts are not shallow:

https://github.com/KSP-CKAN/NetKAN/blob/73a8854c138d2110216d7615119b2baa2f252580/.github/workflows/inflate.yml#L15-L18

So... :shrug:

**Comment by HebaruSan** [comment]
Noted in KSP-CKAN/NetKAN#8522 that it only seems to happen when you add a commit to the branch; just re-running the workflows for the same commit finds the correct netkan.

On such a subsequent commit, the start ref is correct, but `repo.head.commit.hexsha` is somehow a hash that doesn't exist anywhere in the repo history:

```
INFO:root:Looking for changes between 8ddc61e5d71609c0841a3d92418cba52e43b0888 and 3480583443e24e8a8a86b77ff716cdf967fbf6ed
```

```
~/Downloads/KSP/NetKAN $ git show 3480583443e24e8a8a86b77ff716cdf967fbf6ed
fatal: bad object 3480583443e24e8a8a86b77ff716cdf967fbf6ed
```

Maybe `actions/checkout` is synthesizing some kind of hybrid commit to represent ... I don't know??

**Comment by HebaruSan** [comment]
Aha!  https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit

> ## Checkout pull request HEAD commit instead of merge commit
> 
> ```yaml
> - uses: actions/checkout@v2
>   with:
>     ref: ${{ github.event.pull_request.head.sha }}
> ```

It creates a **NEW MERGE COMMIT** for pull requests by default! So when you diff that with the point where the branch was created, of course it includes both changes from the branch and changes from latest master!

I have no idea why they thought that would be wanted at all, let alone enough to make it _the default_ (!!), but at least they explained it and gave a recipe for fixing it.

**Comment by HebaruSan** [comment]
I think this was fixed in https://github.com/KSP-CKAN/NetKAN/commit/f6b1d3a88e38ab229b3e250bd80a272faf6f310c and https://github.com/KSP-CKAN/CKAN-meta/commit/6cc3028b175fa3aad1a610405453fb23e3a28e44. Will re-open if it happens again.

**Comment by HebaruSan** [comment]
It's still doing this! E.g. KSP-CKAN/NetKAN#8587 just inflated DeadlyReentry! :sob:

**Comment by DasSkelett** [comment]
New idea: Find the merge base (last common ancestor), and use the diff of the merge base to the PR HEAD.
Basically `git diff $(git merge-base HEAD master) HEAD`
Tested with https://github.com/KSP-CKAN/NetKAN/pull/8680 (after resetting master to `53d11e635f190a2db010bad2e2235bf92ede82b1`, which was `PR_BASE_SHA` at that point, and checking out new `soc` branch at `1482f375990604a6bd4e01cfc25294a9913848ad` (needs to be fetched first from LGG's NetKAN fork)):
```
$ git diff --name-status $(git merge-base HEAD master) HEAD
D       NetKAN/SimpleOrbitCalculator.frozen
A       NetKAN/SimpleOrbitCalculator.netkan
```
instead of
```
$ git diff --name-status master HEAD
M       NetKAN/Biomatic.netkan
D       NetKAN/SimpleOrbitCalculator.frozen
A       NetKAN/SimpleOrbitCalculator.netkan
```
(which is essentially what we do right now)

**Comment by HebaruSan** [comment]
We don't diff with master, do we? It should be diffing the PR_BASE_SHA with the branch HEAD.

**Comment by DasSkelett** [comment]
> It should be diffing the PR_BASE_SHA with the branch HEAD

> after resetting master to `53d11e635f190a2db010bad2e2235bf92ede82b1`, which was PR_BASE_SHA at that point

```
PR_BASE_SHA: 53d11e635f190a2db010bad2e2235bf92ede82b1

INFO:root:Looking for changes between 53d11e635f190a2db010bad2e2235bf92ede82b1 and 1482f375990604a6bd4e01cfc25294a9913848ad
INFO:root:Start commit sha is 53d11e635f190a2db010bad2e2235bf92ede82b1
```
https://github.com/KSP-CKAN/NetKAN/runs/3171633707

`PR_BASE_SHA` _is_ master, it's the target of the pull request.
No, it doesn't only include changes in the PR, as we can see pretty obviously. Because the PR branch was missing the latest commit of the master branch. Thus the diff "reverts" the latest commit, it does what it's supposed to do, it prints the difference between the two states, or in other words, how to get from the state 1 to state 2, which would be by reverting the additional commit(s) in master that is not in current branch, then applying the own commits that aren't in the master branch.

**Comment by DasSkelett** [comment]
For me this makes perfect sense. No, there's not a ghost commit involved, as you can see from the inflation run log. all commit shas are what I expect them to be, and are available either in master or the source branch.

I mean what can I say, I am able to reproduce the behaviour of the workflow locally, and it matches my expectations. And my proposed solution works locally as well. Both with manual git commands, and when running `ckanmetatester`.

Theoretically I would have a fix here: https://github.com/DasSkelett/xKAN-meta_testing/tree/fix/merge-base-diff

**Comment by HebaruSan** [comment]
OK, if that's the case, then PR_BASE_SHA isn't what I thought it was. I would have expected it to be b605f01b50e8a77c53ec9338be9d9b3947d315bb based on when LGG made his branch. Does the API really not provide the "parent" commit of the PR anywhere?

**Comment by DasSkelett** [comment]
That "parent" commit of the PR would be the merge base commit, no? Doesn't look like it's included in the context / API response per https://docs.github.com/en/rest/reference/pulls. That's why I'd get it inside the workflow, based on the PR_BASE_SHA and the PR HEAD.

**Comment by HebaruSan** [comment]
So originally, it was diffing master (PR_BASE_SHA) with a merge commit (implicitly created by `actions/checkout`)? Ugh.

OK, your idea makes sense to me now. I thought that the API would have included somewhere the data that github.com itself uses to generate the info in the Commits and Files changed tabs. But apparently no, it does the extra logic that you're talking about behind the scenes and never exposes it publicly.

**Comment by HebaruSan** [comment]
Although, maybe we _should_ diff master with a merge commit? The difference between those should be the PR's changes. But then this all should have worked properly at some stage. I need to go back over the whole history of this now to re-understand why various problems happened.

**Comment by HebaruSan** [comment]
> it only seems to happen when you add a commit to the branch; just re-running the workflows for the same commit finds the correct netkan.

Maybe we were diffing the merge commit against the wrong revision of master, or vice versa?

**Comment by HebaruSan** [comment]
> Theoretically I would have a fix here: https://github.com/DasSkelett/xKAN-meta_testing/tree/fix/merge-base-diff

> OK, your idea makes sense to me now.

@DasSkelett, I'm still a bit perplexed by some aspects of this issue, but this idea looks like our best option for a fix, if you have time to make a pull request for it.

**Comment by DasSkelett** [comment]
> EDIT: OK, reviewed the history, and it does seem that it should have been working correctly when this originally was submitted. At that time we were (unknowingly) diffing master with a merge commit, which should have given us the PR's changes only. Need to understand why there was a problem at that time.

Maybe that was while we still had the `GITHUB_` prefixes in the env vars, where they didn't get through to the container?

> Although, maybe we should diff master with a merge commit? The difference between those should be the PR's changes.

Hm, that might be true. I think it would only make a difference if the same file(s) have been edited in the master branch as well.
And then it should usually not have any real effect, as we only care about whether a file changed or not, which it did if it has been changed in both branches. Only if the PR branch somehow reverts the master commit (without having the changes of those master commits in its own history), this would have an effect in the list of validated files, and I'm not sure if this is even possible in Git.

But if I'm not mistaken, this would need to be changed in the workflow yamls to get the automatically generated merge commit again, and not require any additional changes to my branch.
So I'm going to do a PR now with what I have already, that is diffing merge base -> PR HEAD. We can then decide whether we want to switch to a merge commit right away, or maybe try it out without for some time and see what results it gives us.
